import type { Problem, ProblemGenerator } from './types';
import { mulberry32, shuffleWithSeed } from './prng';

export const personalDataClassifier: ProblemGenerator = {
  type: 'law-personal-data-classifier',
  displayName: 'Personal Data Classifier',
  generate(seed: number): Problem {
    const rng = mulberry32(seed);

    const items = [
      // Easy / Clear Cut
      {
        text: "John Doe's personal email address (john.doe@gmail.com)",
        isPersonal: true,
        reason: "It directly identifies a specific natural person."
      },
      {
        text: "Company Registration Number (for a corporation)",
        isPersonal: false,
        reason: "GDPR applies to *natural persons*, not legal entities like corporations."
      },
      {
        text: "A generic info@company.com email address",
        isPersonal: false,
        reason: "It identifies a department, not a specific natural person (unless used by only one known person)."
      },
      
      // Technical / Identifiers
      {
        text: "Dynamic IP Address used by a home user",
        isPersonal: true,
        reason: "The CJEU (Breyer case) ruled that dynamic IP addresses are personal data because the ISP can link them to a subscriber."
      },
      {
        text: "Cookie ID tracking user behavior across sites",
        isPersonal: true,
        reason: "It singles out a specific user's device and behavior, making them identifiable (singling out)."
      },
      {
        text: "GPS coordinates of a delivery driver's phone",
        isPersonal: true,
        reason: "It tracks the location of a specific employee, which is personal data."
      },
      {
        text: "MAC Address of a smartphone",
        isPersonal: true,
        reason: "A MAC address is a unique hardware identifier that singles out a specific device owned by a person."
      },
      {
        text: "Advertising ID (IDFA/GAID) on a phone",
        isPersonal: true,
        reason: "These are unique identifiers designed specifically to track and single out individuals for advertising."
      },

      // Nuanced / Tricky
      {
        text: "Work email: 'firstname.lastname@company.com'",
        isPersonal: true,
        reason: "Even though it is for business, it identifies a specific natural person. Business contact data is still Personal Data."
      },
      {
        text: "Encrypted customer database (without the key)",
        isPersonal: true,
        reason: "Encrypted data is **Pseudonymized**, not Anonymous. If the key exists somewhere (even if you don't have it right now), it's still Personal Data."
      },
      {
        text: "Car License Plate Number",
        isPersonal: true,
        reason: "A license plate can be linked to the owner via government databases, making it personal data."
      },
      {
        text: "Handwritten notes about a candidate during an interview",
        isPersonal: true,
        reason: "If the notes are stored in a filing system (or intended to be), they are Personal Data."
      },
      
      // Not Personal Data
      {
        text: "Anonymized aggregate statistics (e.g., '50% of users are male')",
        isPersonal: false,
        reason: "If the data is truly anonymous and individuals cannot be singled out, it is not personal data."
      },
      {
        text: "Death Certificate of a person who died in 1990",
        isPersonal: false,
        reason: "GDPR does not apply to deceased persons (though national laws might)."
      },
      {
        text: "Weather data (Temperature in London)",
        isPersonal: false,
        reason: "This is environmental data, not related to an identified or identifiable natural person."
      },
      {
        text: "A random number generated by a server (non-unique, not linked to anyone)",
        isPersonal: false,
        reason: "Random noise that cannot be linked to a person is not personal data."
      }
    ];

    const item = items[Math.floor(rng() * items.length)];
    const correct = item.isPersonal ? "Personal Data" : "Not Personal Data";
    const wrong = item.isPersonal ? "Not Personal Data" : "Personal Data";
    
    // Distractors for "Not Personal Data" sometimes get tricky, but binary choice is best here to enforce the definition.
    // To make it harder, we could add "Special Category" but let's stick to the binary classifier for clarity.
    
    const options = shuffleWithSeed([correct, wrong], rng);
    const correctIndex = options.indexOf(correct);

    return {
      question: `Is **"${item.text}"** considered Personal Data under GDPR?`,
      options,
      correctIndex,
      explanation: item.reason
    };
  }
};

export const generators = [personalDataClassifier] as const;
